spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  # Swagger2 사용을 위한 코드
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher